name: aws-s3-temp-bucket-deploy

on:
  pull_request:
    types: [ labeled ]

env:
  NODE_VERSION: 14.x
  LABEL_NAME_TRIGGER: temp-deploy
  AWS_REGION_NAME: eu-central-1
  AWS_TEMP_BUCKET_NAME: dash-pr-temp-d1c5175ca8d73b629

jobs:
  build_job:
    if: ${{ github.event.label.name == env.LABEL_NAME_TRIGGER }}
    name: A job to build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Create S3 Temp Bucket
        run: aws s3api create-bucket --bucket ${{ env.AWS_TEMP_BUCKET_NAME }} --region ${{ env.AWS_REGION_NAME }} --create-bucket-configuration LocationConstraint=${{ env.AWS_REGION_NAME }}
      - name: Create policy
        run: |
          echo '{
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Sid": "PublicReadGetObject",
                        "Principal": "*",
                        "Effect": "Allow",
                        "Action": "s3:GetObject",
                        "Resource": "arn:aws:s3:::${{ env.AWS_TEMP_BUCKET_NAME }}/*"
                    }
                ]
            }' > bucket_policy.json
      - name: Set bucket public policy
        run: aws s3api put-bucket-policy --bucket ${{ env.AWS_TEMP_BUCKET_NAME }} --policy file://bucket_policy.json
      - name: Deploy static to Temp S3 Bucket
        run: aws s3 sync ./public s3://${{ env.AWS_TEMP_BUCKET_NAME }} --delete
      - name: Tell AWS this should be website
        run: aws s3 website s3://${{ env.AWS_TEMP_BUCKET_NAME }}/ --index-document index.html --error-document error.html
