name: aws-s3-temp-bucket-close

on:
  # pull_request:
  # types: [ labeled ]
  push:
    branches:
      - main

env:
  NODE_VERSION: 14.x
  LABEL_NAME_TRIGGER: bug
  AWS_REGION_NAME: eu-central-1
  AWS_TEMP_BUCKET_NAME: dash-pr-temp-d1c5175ca8d73b629

jobs:
  build_job:
    # if: ${{ github.event.label.name == env.LABEL_NAME_TRIGGER }}
    name: A job to build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Empty a bucket's contents
        run: aws s3 rm s3://${{ env.AWS_TEMP_BUCKET_NAME }} --recursive

      - name: Delete S3 Temp Bucket
        run: aws s3api delete-bucket --bucket ${{ env.AWS_TEMP_BUCKET_NAME }} --region ${{ env.AWS_REGION_NAME }}
